services:
  rpc:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - USER_SERVICE_ADDRESS=http://localhost:5001
    ports:
      - "50010:50051"

  mongodb:
    image: mongo
    ports:
      - 27011:27017

  rest_gateway:
    build:
      context: .
      dockerfile: Dockerfile.rest_gateway
    ports:
      - "8081:8081"
    depends_on:
      - rpc
      - mongodb