services:
  item-service-nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=backend:9091
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 8081:80
    depends_on:
      - backend
    networks:
        - user_external
        - default

  backend:
    build: .
    stop_signal: SIGINT #stop gracefully
    environment:
      - FLASK_SERVER_PORT=9091
      - MONGODB_URI=mongodb://mongodb:27017

  mongodb:
    image: mongo
    ports:
      - 27010:27017

networks:
  user_external:
    external: true