services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/userdb 
    depends_on:
      - db
    volumes:
      - .:/app  

  db:
    image: mysql:5.7
    container_name: userdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
