services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=backend:5001
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 8082:80
    depends_on:
      - backend
    networks:
      - external
      - default


  user-service:
    build: .
    environment:
      - MYSQL_URI=mysql+pymysql://root:root@db:3306/userdb
      - MONGODB_URI=mongodb://mongodb:27017
    depends_on:
      - db
      - mongodb

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    ports:
      - "3307:3306"

  mongodb:
    image: mongo

networks:
  external:
    driver: bridge