# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: admin_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'admin_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61\x64min_service.proto\x12\x05\x61\x64min\"$\n\x0e\x41uctionRequest\x12\x12\n\nauction_id\x18\x01 \x01(\t\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"M\n\x0f\x43\x61tegoryRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x13\n\x0b\x63\x61tegory_id\x18\x02 \x01(\t\x12\x15\n\rcategory_name\x18\x03 \x01(\t\"!\n\x0eSortingRequest\x12\x0f\n\x07sort_by\x18\x01 \x01(\t\"#\n\x0eMetricsRequest\x12\x11\n\ttimeframe\x18\x01 \x01(\t\"7\n\x0c\x45mailRequest\x12\x10\n\x08\x65mail_id\x18\x01 \x01(\t\x12\x15\n\rresponse_text\x18\x02 \x01(\t\"-\n\x14\x46laggedItemsResponse\x12\x15\n\rflagged_items\x18\x01 \x03(\t\"1\n\x16\x41\x63tiveAuctionsResponse\x12\x17\n\x0f\x61\x63tive_auctions\x18\x01 \x03(\t\"w\n\x0fMetricsResponse\x12\x34\n\x07metrics\x18\x01 \x03(\x0b\x32#.admin.MetricsResponse.MetricsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xce\x03\n\x0c\x41\x64minService\x12:\n\x10StopAuctionEarly\x12\x15.admin.AuctionRequest\x1a\x0f.admin.Response\x12\x39\n\x12RemoveAndBlockUser\x12\x12.admin.UserRequest\x1a\x0f.admin.Response\x12\x42\n\x17\x41\x64\x64ModifyRemoveCategory\x12\x16.admin.CategoryRequest\x1a\x0f.admin.Response\x12=\n\x10ViewFlaggedItems\x12\x0c.admin.Empty\x1a\x1b.admin.FlaggedItemsResponse\x12J\n\x12ViewActiveAuctions\x12\x15.admin.SortingRequest\x1a\x1d.admin.ActiveAuctionsResponse\x12?\n\x0e\x45xamineMetrics\x12\x15.admin.MetricsRequest\x1a\x16.admin.MetricsResponse\x12\x37\n\x0fRespondToEmails\x12\x13.admin.EmailRequest\x1a\x0f.admin.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'admin_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICSRESPONSE_METRICSENTRY']._loaded_options = None
  _globals['_METRICSRESPONSE_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_AUCTIONREQUEST']._serialized_start=30
  _globals['_AUCTIONREQUEST']._serialized_end=66
  _globals['_USERREQUEST']._serialized_start=68
  _globals['_USERREQUEST']._serialized_end=98
  _globals['_CATEGORYREQUEST']._serialized_start=100
  _globals['_CATEGORYREQUEST']._serialized_end=177
  _globals['_SORTINGREQUEST']._serialized_start=179
  _globals['_SORTINGREQUEST']._serialized_end=212
  _globals['_METRICSREQUEST']._serialized_start=214
  _globals['_METRICSREQUEST']._serialized_end=249
  _globals['_EMAILREQUEST']._serialized_start=251
  _globals['_EMAILREQUEST']._serialized_end=306
  _globals['_FLAGGEDITEMSRESPONSE']._serialized_start=308
  _globals['_FLAGGEDITEMSRESPONSE']._serialized_end=353
  _globals['_ACTIVEAUCTIONSRESPONSE']._serialized_start=355
  _globals['_ACTIVEAUCTIONSRESPONSE']._serialized_end=404
  _globals['_METRICSRESPONSE']._serialized_start=406
  _globals['_METRICSRESPONSE']._serialized_end=525
  _globals['_METRICSRESPONSE_METRICSENTRY']._serialized_start=479
  _globals['_METRICSRESPONSE_METRICSENTRY']._serialized_end=525
  _globals['_RESPONSE']._serialized_start=527
  _globals['_RESPONSE']._serialized_end=554
  _globals['_EMPTY']._serialized_start=556
  _globals['_EMPTY']._serialized_end=563
  _globals['_ADMINSERVICE']._serialized_start=566
  _globals['_ADMINSERVICE']._serialized_end=1028
# @@protoc_insertion_point(module_scope)
